# Generated by Django 6.0.7 on 2026-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('pesticides', '0002_pesticide_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='recommended_pesticides',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='pesticides.pesticide'),
        ),
    ]
