# Generated by Django 6.0.7 on 2026-09-02 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crop_options_alter_crop_image_alter_crop_name_and_more'),
        ('disease', '0002_disease_recommended_pesticides'),
        ('pesticides', '0003_alter_pesticide_options_alter_pesticide_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images/'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['crop', 'name'], name='disease_dis_crop_id_37f002_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['crop', 'severity'], name='disease_dis_crop_id_90e3ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='disease',
            constraint=models.UniqueConstraint(fields=('crop', 'name'), name='unique_disease_per_crop'),
        ),
    ]
