# Generated by Django 6.0.7 on 2026-08-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='disease.disease')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='pesticides.pesticide')),
            ],
            options={
                'unique_together': {('disease', 'pesticide')},
            },
        ),
    ]
