# Generated by Django 6.0.7 on 2026-08-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='crop_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_range', models.CharField(max_length=100)),
                ('packing_size', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=255)),
                ('spray_method', models.TextField()),
                ('precautions', models.TextField()),
                ('image', models.ImageField(upload_to='pesticide_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='recommendations.crop')),
                ('recommended_pesticides', models.ManyToManyField(blank=True, related_name='diseases', to='recommendations.pesticide')),
            ],
        ),
    ]
