# Generated by Django 6.0.7 on 2026-09-02 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
