# Generated by Django 6.0.7 on 2026-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_range', models.CharField(max_length=100)),
                ('packing_size', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=255)),
                ('spray_method', models.TextField()),
                ('precautions', models.TextField()),
                ('image', models.ImageField(upload_to='pesticide_images/')),
            ],
        ),
    ]
