# Generated by Django 6.0.7 on 2026-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
