# Generated by Django 6.0.7 on 2026-09-02 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0002_pesticide_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticide',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='availability',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='company_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pesticide_images/'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='name',
            field=models.CharField(db_index=True, max_length=150, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddIndex(
            model_name='pesticide',
            index=models.Index(fields=['name', 'company_name'], name='pesticides__name_3b6c6a_idx'),
        ),
    ]
