# Generated by Django 6.0.7 on 2026-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0003_alter_pesticide_options_alter_pesticide_availability_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pesticide',
            constraint=models.UniqueConstraint(fields=('name', 'company_name'), name='unique_pesticide_name_company'),
        ),
    ]
