# Generated by Django 6.0.7 on 2026-10-01 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0004_pesticide_unique_pesticide_name_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticide',
            options={'ordering': ['product_name', 'name']},
        ),
        migrations.AddField(
            model_name='pesticide',
            name='active_ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='application_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='company_manufacturer',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='crop_stage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='dosage_rate',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='formulation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='last_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='packaging',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='pesticide_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='pesticide_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='price_information',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='product_image_url_reference',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='product_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='safety_precautions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='target_crops',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='target_disease_pest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='water_volume_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='pesticide',
            index=models.Index(fields=['product_name', 'company_manufacturer'], name='pesticides__product_277e45_idx'),
        ),
    ]
