# Generated by Django 6.0.7 on 2026-10-01 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0005_alter_pesticide_options_pesticide_active_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='packing_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='precautions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='price_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='spray_method',
            field=models.TextField(blank=True, default=''),
        ),
    ]
